
export const APPLICATION_FORM_REQUEST = 'APPLICATION_FORM_REQUEST'
export const APPLICATION_FORM_SUCCESS = 'APPLICATION_FORM_SUCCESS'
export const APPLICATION_FORM_FAILURE = 'APPLICATION_FORM_FAILURE'

export const INQUIRY_FORM_REQUEST = 'INQUIRY_FORM_REQUEST'
export const INQUIRY_FORM_SUCCESS = 'INQUIRY_FORM_SUCCESS'
export const INQUIRY_FORM_FAILURE = 'INQUIRY_FORM_FAILURE'

